"""HTTP integration tests using generated bytes and temporary destinations only."""
import concurrent.futures
import errno
import hashlib
import http.client
import json
from pathlib import Path
import tempfile
import threading
import unittest
from unittest.mock import patch
from server import copy_paths, make_server


def sha(data):
    return hashlib.sha256(data).hexdigest()


class DestinationTest(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.base = Path(self.temp.name)
        self.archive, self.imports, self.extra = [self.base / n for n in ('archive', 'import', 'extra')]
        for path in (self.archive, self.imports, self.extra):
            path.mkdir()
        self.start()

    def start(self):
        self.server = make_server(self.archive, 'synthetic-token', port=0,
                                  database=self.base / 'index.sqlite3', destinations=[self.imports, self.extra])
        self.thread = threading.Thread(target=self.server.serve_forever, daemon=True)
        self.thread.start()

    def stop(self):
        self.server.shutdown()
        self.server.server_close()
        self.thread.join()
        self.server.inventory.db.close()

    def tearDown(self):
        self.stop()
        self.temp.cleanup()

    def request(self, method, path, data=None, headers=None):
        connection = http.client.HTTPConnection(*self.server.server_address, timeout=10)
        connection.request(method, path, data, {'Authorization': 'Bearer synthetic-token', **(headers or {})})
        response = connection.getresponse()
        result = response.status, json.loads(response.read())
        connection.close()
        return result

    def put(self, data=b'synthetic photo', previous=None):
        headers = {'X-Content-SHA256': sha(data)}
        if previous:
            headers['X-Replace-SHA256'] = previous
        return self.request('PUT', '/v1/files/synthetic.jpg', data, headers)[0]

    def status(self, data=b'synthetic photo'):
        code, result = self.request('POST', '/v1/refresh', '{}')
        self.assertEqual(200, code)
        code, result = self.request('POST', '/v1/check', json.dumps({'generation': result['generation'],
            'items': [{'name': 'synthetic.jpg', 'sha256': sha(data)}]}))
        self.assertEqual(200, code)
        return result['items'][0]['status']

    def test_end_to_end_all_destinations_and_consumed_import(self):
        self.assertEqual('missing', self.status())
        self.assertEqual(201, self.put())
        for root in (self.archive, self.imports, self.extra):
            self.assertEqual(b'synthetic photo', (root / 'synthetic.jpg').read_bytes())
            self.assertFalse(list(root.glob('.incoming-*')))
        self.assertEqual('synced', self.status())
        self.assertEqual(0o644, (self.imports / 'synthetic.jpg').stat().st_mode & 0o777)
        (self.imports / 'synthetic.jpg').unlink()  # PhotoPrism consumed the import.
        self.stop()
        self.start()
        self.assertEqual('synced', self.status())
        self.assertEqual(201, self.put())
        self.assertFalse((self.imports / 'synthetic.jpg').exists())

    def test_partial_failure_survives_restart_and_retry(self):
        original = self.server.inventory.deliveries.available
        def fail_last(index):
            if index == 1:
                raise OSError(errno.ENOSPC, 'synthetic destination unavailable')
            original(index)
        with patch.object(self.server.inventory.deliveries, 'available', side_effect=fail_last):
            self.assertEqual(503, self.put())
        self.assertTrue((self.archive / 'synthetic.jpg').exists())
        self.assertTrue((self.imports / 'synthetic.jpg').exists())
        self.assertFalse((self.extra / 'synthetic.jpg').exists())
        (self.imports / 'synthetic.jpg').unlink()
        self.stop()
        self.start()
        self.assertEqual('missing', self.status())
        self.assertEqual(201, self.put())
        self.assertEqual('synced', self.status())
        self.assertFalse((self.imports / 'synthetic.jpg').exists())
        self.assertEqual(b'synthetic photo', (self.extra / 'synthetic.jpg').read_bytes())

    def test_secondary_conflict_is_preserved_and_retryable(self):
        target = self.imports / 'synthetic.jpg'
        target.write_bytes(b'unrelated contents')
        self.assertEqual(503, self.put())
        self.assertEqual(b'unrelated contents', target.read_bytes())
        self.assertEqual('missing', self.status())
        target.unlink()
        self.assertEqual(201, self.put())
        self.assertEqual('synced', self.status())

    def test_confirmed_replacement_reaches_all_destinations(self):
        self.assertEqual(201, self.put())
        self.assertEqual(409, self.put(b'new synthetic photo'))
        self.assertEqual(201, self.put(b'new synthetic photo', sha(b'synthetic photo')))
        for root in (self.archive, self.imports, self.extra):
            self.assertEqual(b'new synthetic photo', (root / 'synthetic.jpg').read_bytes())

    def test_replacing_back_to_an_earlier_version_delivers_again(self):
        self.assertEqual(201, self.put())
        self.assertEqual(201, self.put(b'new', sha(b'synthetic photo')))
        self.assertEqual(201, self.put(b'synthetic photo', sha(b'new')))
        self.assertEqual(b'synthetic photo', (self.imports / 'synthetic.jpg').read_bytes())

    def test_missing_copy_directory_affects_health_and_remains_pending(self):
        self.imports.rename(self.base / 'offline')
        self.assertEqual(503, self.request('GET', '/health')[0])
        self.assertEqual(503, self.put())
        self.assertEqual('missing', self.status())
        (self.base / 'offline').rename(self.imports)
        self.assertEqual(200, self.request('GET', '/health')[0])
        self.assertEqual(201, self.put())

    def test_bad_hash_never_copies_and_symlinks_never_overwritten(self):
        self.assertEqual(422, self.request('PUT', '/v1/files/synthetic.jpg', b'bad', {'X-Content-SHA256': sha(b'good')})[0])
        self.assertEqual([], list(self.imports.iterdir()))
        target = self.base / 'other.jpg'
        target.write_bytes(b'keep')
        (self.imports / 'synthetic.jpg').symlink_to(target)
        self.assertEqual(503, self.put())
        self.assertEqual(b'keep', target.read_bytes())

    def test_concurrent_retries_do_not_duplicate_copies(self):
        with concurrent.futures.ThreadPoolExecutor(max_workers=4) as pool:
            self.assertEqual([201] * 4, list(pool.map(lambda _: self.put(), range(4))))
        self.assertEqual(['synthetic.jpg'], [p.name for p in self.imports.iterdir()])

    def test_logs_explain_copy_failure_without_private_values(self):
        with self.assertLogs('photosync.camera', level='INFO') as captured:
            with patch.object(self.server.inventory.deliveries, 'available', side_effect=OSError(errno.ENOSPC, 'private-detail')):
                self.assertEqual(503, self.put())
            # Synchronize with the request handler's final log record.
            import time
            deadline = time.monotonic() + 2
            while not captured.records and time.monotonic() < deadline:
                time.sleep(.01)
        records = [json.loads(r.getMessage()) for r in captured.records]
        failure = next(r for r in records if r.get('status') == 503)
        self.assertEqual('copy_delivery_failed', failure['reason'])
        self.assertEqual(1, failure['copy_destination'])
        self.assertEqual(0, failure['copies_completed'])
        self.assertEqual(errno.ENOSPC, failure['errno'])
        for private in ('synthetic.jpg', 'synthetic-token', str(self.base), sha(b'synthetic photo'), 'private-detail'):
            self.assertNotIn(private, json.dumps(records))

    def test_config_validation(self):
        self.assertEqual(['/one', '/two'], copy_paths('["/one","/two"]'))
        for value in ('{}', '[null]', '["relative"]', '[""]'):
            with self.assertRaises(ValueError):
                copy_paths(value)
        for destinations in ([self.archive], [self.imports, self.imports], [self.base], [self.base / 'missing']):
            with self.assertRaises(ValueError):
                make_server(self.archive, 'token', port=0, database=':memory:', destinations=destinations)
